# SonarCloud Project Configuration
sonar.projectKey=HemantKaushik01_Inkwell
sonar.organization=hemantkaushik01
sonar.token=ef5b76867b137e5470f6b0f8c8137c7ba8d063a8

# This is the name and version displayed in the SonarCloud UI.
# sonar.projectName=Inkwell Frontend
# sonar.projectVersion=1.0

# Path to the source directories (relative to the sonar-project.properties file)
sonar.sources=src

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=node_modules/**, dist/**, **/*.test.jsx, **/*.test.js

# SonarCloud Host URL
sonar.host.url=https://sonarcloud.io
